title: CS 1112 SP26
description: Website for the CS 1112 students
theme: just-the-docs

url: https://Quole0812.github.io/CS1112-SP2026

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/Quole0812/CS1112-F2025